---
# bundle exec autostacker24 update --template ec2/cf-templates/debug-security-group.yaml --param VPCStackName=vpc-TEAM_NAME --param TeamName=TEAM_NAME --stack vpc-TEAM_NAME-debug-sg
# bundle exec autostacker24 delete --stack debug-sg-TEAM_NAME
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VPCStackName:
    Type: String
  TeamName:
    Type: String

Resources:

  DebugSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow ssh access through instance"
      VpcId: !ImportValue {"Fn::Sub": "${VPCStackName}-VPCId"}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: !Sub "${TeamName}-ssh-debug"
