---
# bundle exec autostacker24 update --template lambda/cf-templates/chatbot.yaml --stack lambda-chatbot-TEAM_NAME
# bundle exec autostacker24 delete --stack lambda-chatbot-TEAM_NAME
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  TeamName:
    Type: String

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "chatbot-${TeamName}"
      Code:
        ZipFile: >
          exports.handler = function(event, context) {
            console.log("running code");
            context.succeed("done");
          };
      Handler: "index.handler"
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      Runtime: "nodejs6.10"
      Timeout: "5"

  CronEvent:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "trigger-chatbot-${TeamName}"
      ScheduleExpression: cron(0/10 * * * ? *)
      Targets:
        - Arn:
            Fn::GetAtt: [ LambdaFunction , "Arn" ]
          Id: !Ref LambdaFunction
