---
# bundle exec autostacker24 update --template lambda/cf-templates/chatbot.yaml --stack lambda-chatbot-TEAM_NAME
# bundle exec autostacker24 delete --stack lambda-chatbot-TEAM_NAME
AWSTemplateFormatVersion: '2010-09-09'

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          exports.handler = function(event, context) {
            console.log("running code");
            context.succeed("done");
          };
      Handler: "index.handler"
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      Runtime: "nodejs6.10"
      Timeout: "5"
